### ISSUE TITLE
Consider whether we need root/work dir config

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev-lint#3]
See point 3 in https://github.com/ckeditor/ckeditor5/issues/262#issuecomment-234942214.

**Comment by Reinmar** [comment]
There's https://github.com/ckeditor/ckeditor5-dev-task-lint/blob/master/gulpfile.js#L7 defined now. It's not used anywhere, so if we don't need any configuration like this it should be removed.

**Comment by pomek** [comment]
Moved to: https://github.com/ckeditor/ckeditor5-dev/issues/31.
